[package]
name = "nefsm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = {version="1.0.107",features=["full","fold"]}
quote = "1.0.23"


[dev-dependencies]
